# Base de datos
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=booklibrary
quarkus.datasource.password=booklibrary
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5436/booklibrary

# Hibernate
# quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=true

# Puerto
quarkus.http.port=8080

# Swagger UI
quarkus.swagger-ui.always-include=true

# JWT
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=book-library-security
smallrye.jwt.sign.key.location=privateKey.pem

# Seguridad — activa la autenticación JWT
quarkus.http.auth.permission.authenticated.paths=/api/*
quarkus.http.auth.permission.authenticated.policy=authenticated

quarkus.http.auth.permission.public.paths=/auth/*, /q/*
quarkus.http.auth.permission.public.policy=permit